# Generated by Django 5.2 on 2025-04-06 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='outgoing',
            name='amount',
        ),
    ]
